line-length = 120
exclude = ["./.venv/*", "./migrations/"]
target-version = "py313"

[lint]
select = ["ALL"]
ignore = [
    "D101",     #   [ ] undocumented-public-class
    "D102",     #   [ ] undocumented-public-method
    "D100",     #   [ ] undocumented-public-module
    "D103",     #   [ ] undocumented-public-function
    "D107",     #   [ ] undocumented-public-init
    "D203",     #   [ ] no-blank-line-before-class
    "D213",     #   [ ] multi-line-summary-second-line
    "D104",     #   [ ] undocumented-public-package
    "COM812",   # Conflicts with formatter
    "S101",    
]

[lint.flake8-quotes]
inline-quotes = "single"

[lint.flake8-tidy-imports]
ban-relative-imports = 'parents'

[lint.flake8-annotations]
suppress-none-returning = true
allow-star-arg-any = true
suppress-dummy-args = true

[lint.pylint]
max-args = 10


[format]
quote-style = "single"
