"""Init

Revision ID: 4ee07a7b7ea2
Revises:
Create Date: 2025-10-26 15:15:39.668293

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '4ee07a7b7ea2'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'buildings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('address', sa.String(), nullable=False),
        sa.Column(
            'point',
            geoalchemy2.types.Geography(
                geometry_type='POINT', dimension=2, from_text='ST_GeogFromText', name='geography', nullable=False
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index('idx_buildings_point', 'buildings', ['point'], unique=False, postgresql_using='gist', if_not_exists=True)
    op.create_table(
        'organizations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('phone', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'specializations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['parent_id'], ['specializations.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'organization_buildings',
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('building_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['building_id'], ['buildings.id']),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id']),
        sa.PrimaryKeyConstraint('organization_id'),
    )
    op.create_table(
        'organization_specializations',
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('specialization_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id']),
        sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id']),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('organization_specializations')
    op.drop_table('organization_buildings')
    op.drop_table('specializations')
    op.drop_table('organizations')
    op.drop_index('idx_buildings_point', table_name='buildings', postgresql_using='gist')
    op.drop_table('buildings')
