"""Init

Revision ID: init
Revises:
Create Date: 2025-10-27 19:53:09.131425

"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'init'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'buildings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('address', sa.String(), nullable=False),
        sa.Column(
            'point',
            geoalchemy2.types.Geography(
                geometry_type='POINT',
                srid=4326,
                dimension=2,
                from_text='ST_GeogFromText',
                name='geography',
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column('search_vector', postgresql.TSVECTOR(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'organizations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('phone', sa.String(), nullable=False),
        sa.Column('search_vector', postgresql.TSVECTOR(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'specializations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['parent_id'], ['specializations.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'organization_buildings',
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('building_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['building_id'], ['buildings.id']),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id']),
        sa.PrimaryKeyConstraint('organization_id'),
    )
    op.create_table(
        'organization_specializations',
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('specialization_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id']),
        sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id']),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_specializations')
    op.drop_table('organization_buildings')
    op.drop_table('specializations')
    op.drop_table('organizations')
    op.drop_table('buildings')
    # ### end Alembic commands ###
